version: '3.8'

services:
  # MongoDB Service
  mongodb:
    image: mongo:7
    container_name: lead-scoring-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: lead-scoring
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  # API Service
  api:
    build: .
    container_name: lead-scoring-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGODB_URI: mongodb://mongodb:27017/lead-scoring
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
    depends_on:
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:

